### ISSUE TITLE
ERR : topic /sensor_msgs/msg/Image with type ffmpeg_image_transport_msgs/msg/FFMPEGPacket not found!

### ISSUE THREAD

**Issue by git-sachin1066** [ros-misc-utilities/ffmpeg_image_transport_tools#1]
Hello, Thanks alot for helping us with your amazing work.
I am trying to run your codebase on my data. I have certain questions/ error here.

i am trying to run 

1. _ros2 run ffmpeg_image_transport_tools bag_to_file -t **/sensor_msgs/msg/Image** -r 40 -b ./aa/aa.db3_

in that account i am encountered with this error: 

_opening bag: ./aa/aa.db3
topic:       /sensor_msgs/msg/Image

closing.

closing.
[INFO] [1714139715.765158678] [rosbag2_storage]: Opened database '***/aa/aa.db3' for READ_ONLY.
topic /sensor_msgs/msg/Image with type ffmpeg_image_transport_msgs/msg/FFMPEGPacket not found!
terminate called after throwing an instance of 'std::runtime_error'
  what():  topic not found!
[ros2run]: Aborted
_

2. there is one option -e , how you assume a good value for this
3. In section, **Extract frames from a rosbag**, how to get bag_to_frames, it says command not found.

I am little stuck now on this.
FYI 

-  i had rosbag (*.bag) previously, i changed it to ros2 compatible file (*.db3) using some python package

_https://pypi.org/project/rosbags/_

-  also, **/sensor_msgs/msg/Image** is my topic i got from the row of db3 file when read using sqllite

![image](https://github.com/ros-misc-utilities/ffmpeg_image_transport_tools/assets/67868141/f3ecb4e2-ac8c-4ea3-bacb-5b7fc859f336)

**Comment by berndpfrommer** [comment]
Please check the spelling of your topic. Topics are capitalization sensitive.

**Comment by git-sachin1066** [comment]
Thanks for your response. 
Even though following this way i encounter same error 

`ros2 bag info ./aa.db3`

![image](https://github.com/ros-misc-utilities/ffmpeg_image_transport_tools/assets/67868141/e7ab3858-6f92-456d-916f-f78e4b7eee16)


`ros2 run ffmpeg_image_transport_tools bag_to_file -t **/interfacea/link3/image/h264** -b ./rosbag/aa/ -e 1710085164.466 -r 40`
gives me the same result 
opening bag: ./rosbag/aa/
topic:       /interfacea/link3/image/h264
[INFO] [1714481338.725989095] [rosbag2_storage]: Opened database '/home/vclab/sachin/nerf/napdata/rosbag/aa/aa.db3' for READ_ONLY.
topic /interfacea/link3/image/h264 with type ffmpeg_image_transport_msgs/msg/FFMPEGPacket not found!
terminate called after throwing an instance of 'std::runtime_error'
  what():  topic not found!
[ros2run]: Aborted

/interfacea/link3/image/h264 i am taking from the output from the first command.

**Comment by berndpfrommer** [comment]
Yeah, but where do you get the idea from to put ** in front of and after the topic? And besides, the message type says ``sensor_msgs/msg/CompressedImage``. This bag has not been recorded with ffmpeg packets, but with a compressed transport (which uses different compression). When you do ros2 bag info <bag> you should see Type: ``ffmpeg_image_transport_msgs/msg/FFMPEGPacket``.
The error message actually says that it was looking for the ffmpeg type.

**Comment by git-sachin1066** [comment]
i wanted to make it bold, to highlight my topic name, the star i am getting becuse of B icon  in the text field
![image](https://github.com/ros-misc-utilities/ffmpeg_image_transport_tools/assets/67868141/345f3ef1-91f6-45f6-b22f-f7376e8e8edc)

my code is  is this 


![image](https://github.com/ros-misc-utilities/ffmpeg_image_transport_tools/assets/67868141/ca660bb0-7941-4d4a-a66d-3a29ebd7c745)

**Comment by berndpfrommer** [comment]
Please top sending images, but learn how to use markdown and code blocks instead. It's the ``<>`` symbol. And there is a "preview" window where you can check how your message looks before you post it.
